"""《亂世演算_征佔紀元》世界地圖第一階段全域參數。"""

# 地圖尺寸：2000×2000 = 4,000,000 個正方形格。
MAP_WIDTH = 2000
MAP_HEIGHT = 2000
MAP_SEED = 20260924

# RANDOM 會從下列風格中依 Seed 穩定抽選。
WORLD_STYLE = "BALANCED"
WORLD_STYLE_OPTIONS = (
    "BALANCED",       # 均衡世界
    "SUPERCONTINENT", # 超級大陸
    "ARCHIPELAGO",    # 群島世界
    "FRACTURED",      # 破碎大陸
    "INLAND_SEAS",    # 內海世界
    "TWIN_CONTINENTS",# 雙大陸世界
)

# 海陸、大陸與島嶼。
TARGET_OCEAN_RATIO = 0.70
CONTINENT_CORE_MIN = 4
CONTINENT_CORE_MAX = 9
MIN_ISLAND_AREA = 24
COAST_SMOOTHING_ITERATIONS = 1

# 地形形狀。
DOMAIN_WARP_STRENGTH = 0.055
CONTINENT_NOISE_STRENGTH = 0.42
COAST_DETAIL_STRENGTH = 0.18
ISLAND_CHAIN_STRENGTH = 0.12

# 板塊與山系。
TECTONIC_PLATE_MIN = 9
TECTONIC_PLATE_MAX = 16
MOUNTAIN_STRENGTH = 0.22
MOUNTAIN_WIDTH = 9.0

# 地形分類相對海平面的高度。
DEEP_OCEAN_DEPTH = 0.12
BEACH_HEIGHT = 0.025
PLAIN_HEIGHT = 0.16
HILL_HEIGHT = 0.30
MOUNTAIN_HEIGHT = 0.34

# 顯示與存檔。
CHUNK_SIZE = 256
PREVIEW_FILENAME = "world_map_preview.png"
DATA_FILENAME = "world_map.npz"
INFO_FILENAME = "world_map_info.json"
