"""《亂世演算_征佔紀元》V6 世界、拓荒、戰爭與UI全域參數。"""

# 地圖尺寸：2000×2000 = 4,000,000 個正方形格。
MAP_WIDTH = 2000
MAP_HEIGHT = 2000
MAP_SEED = 20260924

# RANDOM 會從下列風格中依 Seed 穩定抽選。
WORLD_STYLE = "BALANCED"
WORLD_STYLE_OPTIONS = (
    "BALANCED",       # 均衡世界
    "SUPERCONTINENT", # 超級大陸
    "ARCHIPELAGO",    # 群島世界
    "FRACTURED",      # 破碎大陸
    "INLAND_SEAS",    # 內海世界
    "TWIN_CONTINENTS",# 雙大陸世界
)

# 海陸、大陸與島嶼。
TARGET_OCEAN_RATIO = 0.70
CONTINENT_CORE_MIN = 4
CONTINENT_CORE_MAX = 9
MIN_ISLAND_AREA = 24
COAST_SMOOTHING_ITERATIONS = 1

# 地形形狀。
DOMAIN_WARP_STRENGTH = 0.055
CONTINENT_NOISE_STRENGTH = 0.42
COAST_DETAIL_STRENGTH = 0.18
ISLAND_CHAIN_STRENGTH = 0.12

# 板塊與山系。
TECTONIC_PLATE_MIN = 9
TECTONIC_PLATE_MAX = 16
MOUNTAIN_STRENGTH = 0.22
MOUNTAIN_WIDTH = 9.0

# 地形分類相對海平面的高度。
DEEP_OCEAN_DEPTH = 0.12
BEACH_HEIGHT = 0.025
PLAIN_HEIGHT = 0.16
HILL_HEIGHT = 0.30
MOUNTAIN_HEIGHT = 0.34

# 顯示與存檔。
CHUNK_SIZE = 256
PREVIEW_FILENAME = "world_map_preview.png"
DATA_FILENAME = "world_map.npz"
INFO_FILENAME = "world_map_info.json"

# 第二階段：水文密度（以2000×2000為基準，小地圖會按面積縮放）。
LAKE_COUNT = 18
RIVER_SOURCE_COUNT = 85

# 第四階段：國家、領土與交通。
COUNTRY_COUNT = 32
COUNTRY_MIN_DISTANCE_RATIO = 0.075
MIN_COUNTRY_LANDMASS_CELLS = 12000
TERRITORY_RADIUS_RATIO = 0.42
TERRITORY_ALPHA = 0.34
TERRITORY_CELLS_PER_CITY = 45000
MAX_CITIES_PER_COUNTRY = 5
PORTS_PER_COUNTRY = 2

# 第五階段：時間、人口、資源與軍事。
WAR_START_YEAR = 1
INITIAL_POPULATION_PER_CELL = 2.4
INITIAL_SOLDIER_RATIO = 0.08
INITIAL_FLEET_PER_PORT = 18
ANNUAL_POPULATION_GROWTH = 0.006
ANNUAL_RECRUIT_RATIO = 0.012
MIN_GARRISON_RATIO = 0.035

# 糧食經濟：所有已控制的可居住格都按農業值生產，人口成長受承載量限制。
FOOD_PRODUCTION_MULTIPLIER = 1.15
FOOD_CONSUMPTION_PER_PERSON = 0.18
FOOD_GROWTH_RESERVE_RATIO = 0.90
CITY_FOOD_PRODUCTIVITY_BONUS = 0.015
MAX_CITY_FOOD_PRODUCTIVITY_BONUS = 0.30

# 行軍與補給。距離以地圖格計，1回合等於1年。
LAND_MARCH_CELLS_PER_YEAR = 38.0
SEA_MARCH_CELLS_PER_YEAR = 75.0
NAVAL_OPERATION_RANGE = 620.0
SUPPLY_PER_SOLDIER_CELL = 0.000018
SUPPLY_SHORTAGE_ATTRITION = 0.12
MOUNTAIN_DEFENSE_BONUS = 0.55
HILL_DEFENSE_BONUS = 0.22
RIVER_DEFENSE_BONUS = 0.12
AMPHIBIOUS_ATTACK_PENALTY = 0.28

# AI與戰爭節奏。
AI_WAR_CHECK_INTERVAL = 5
AI_BASE_WAR_CHANCE = 0.10
AI_MIN_ATTACK_SOLDIERS = 800
AI_MIN_POWER_RATIO = 1.08
AI_MAX_ACTIVE_CAMPAIGNS = 2
COALITION_THREAT_SHARE = 0.16
COALITION_MAX_MEMBERS = 5
CAPTURE_RADIUS_MIN = 10
CAPTURE_RADIUS_MAX = 36
BATTLE_RANDOMNESS = 0.12

# 聯盟援軍需要實際行軍；援助比例不會瞬間加到戰場。
ALLIANCE_COUNT = 6
ALLIANCE_REINFORCEMENT_RATIO = 0.18

# V6時間與UI：1回合=1年，正常速度每2秒推進1年。
SECONDS_PER_YEAR = 0.01
AUTO_RUN_ON_START = True
COUNTRY_NAME_FONT_SIZE = 12
COUNTRY_NAME_FONT_BOLD = True
COUNTRY_NAME_OUTLINE_WIDTH = 2
LEFT_PANEL_WIDTH = 330
RIGHT_PANEL_WIDTH = 430
UI_REFRESH_EVERY_YEARS = 1

# V7 國家延續、遷都、分裂與君主制度（皆為可調整的全域變數）。
CAPITAL_RELOCATION_MIN_CITIES = 2       # 首都失守後，至少需多少座剩餘城市才能推舉新王。
CAPITAL_RELOCATION_CITY_RADIUS = 80     # 判斷城市群密集程度的半徑（地圖格）。
CAPITAL_RELOCATION_MIN_TERRITORY = 50  # 允許遷都的最低剩餘領土格數。
CAPITAL_RELOCATION_MIN_POPULATION = 80 # 允許遷都的最低剩餘人口。
TERRITORY_SPLIT_GRACE_YEARS = 20       # 主要領土斷裂持續幾年後才正式分裂。
TERRITORY_SPLIT_MIN_CELLS = 30         # 每個分裂主體至少需要的領土格數。
TERRITORY_SPLIT_MIN_SHARE = 0.15       # 每個分裂主體至少占原國領土的比例。
KING_REIGN_MIN_YEARS = 70              # 國王最短在位年數。
KING_REIGN_MAX_YEARS = 90              # 國王最長在位年數，平均約80年。

# V6拓荒：開局只有首都周圍的小型核心領土。
INITIAL_TERRITORY_RADIUS = 7
INITIAL_TERRITORY_MAX_CELLS = 150
EXPANSION_INTERVAL_YEARS = 5
BASE_EXPANSION_CELLS = 2
EXPANSION_CELLS_PER_SOLDIER = 4
EXPANSION_FOOD_COST_PER_CELL = 0.8
EXPANSION_TIMBER_COST_PER_CELL = 0.35
SETTLER_POPULATION_PER_CELL = 1

# 建築會增加影響範圍或軍事拓荒能力。
BUILDING_CHECK_INTERVAL_YEARS = 10
CITY_AREA_PER_BUILDING = 180
BARRACKS_AREA_PER_BUILDING = 130
OUTPOST_AREA_PER_BUILDING = 90
CITY_EXPANSION_BONUS = 2
BARRACKS_EXPANSION_BONUS = 3
OUTPOST_EXPANSION_BONUS = 2
CITY_COST = (80.0, 120.0, 45.0)       # 糧食、木材、礦產
BARRACKS_COST = (55.0, 75.0, 90.0)
OUTPOST_COST = (35.0, 55.0, 25.0)
PORT_COST = (60.0, 130.0, 70.0)
