"""《亂世演算_征佔紀元》V5 世界與空間戰爭全域參數。"""

# 地圖尺寸：2000×2000 = 4,000,000 個正方形格。
MAP_WIDTH = 2000
MAP_HEIGHT = 2000
MAP_SEED = 20260924

# RANDOM 會從下列風格中依 Seed 穩定抽選。
WORLD_STYLE = "BALANCED"
WORLD_STYLE_OPTIONS = (
    "BALANCED",       # 均衡世界
    "SUPERCONTINENT", # 超級大陸
    "ARCHIPELAGO",    # 群島世界
    "FRACTURED",      # 破碎大陸
    "INLAND_SEAS",    # 內海世界
    "TWIN_CONTINENTS",# 雙大陸世界
)

# 海陸、大陸與島嶼。
TARGET_OCEAN_RATIO = 0.70
CONTINENT_CORE_MIN = 4
CONTINENT_CORE_MAX = 9
MIN_ISLAND_AREA = 24
COAST_SMOOTHING_ITERATIONS = 1

# 地形形狀。
DOMAIN_WARP_STRENGTH = 0.055
CONTINENT_NOISE_STRENGTH = 0.42
COAST_DETAIL_STRENGTH = 0.18
ISLAND_CHAIN_STRENGTH = 0.12

# 板塊與山系。
TECTONIC_PLATE_MIN = 9
TECTONIC_PLATE_MAX = 16
MOUNTAIN_STRENGTH = 0.22
MOUNTAIN_WIDTH = 9.0

# 地形分類相對海平面的高度。
DEEP_OCEAN_DEPTH = 0.12
BEACH_HEIGHT = 0.025
PLAIN_HEIGHT = 0.16
HILL_HEIGHT = 0.30
MOUNTAIN_HEIGHT = 0.34

# 顯示與存檔。
CHUNK_SIZE = 256
PREVIEW_FILENAME = "world_map_preview.png"
DATA_FILENAME = "world_map.npz"
INFO_FILENAME = "world_map_info.json"

# 第二階段：水文密度（以2000×2000為基準，小地圖會按面積縮放）。
LAKE_COUNT = 18
RIVER_SOURCE_COUNT = 85

# 第四階段：國家、領土與交通。
COUNTRY_COUNT = 32
COUNTRY_MIN_DISTANCE_RATIO = 0.075
MIN_COUNTRY_LANDMASS_CELLS = 12000
TERRITORY_RADIUS_RATIO = 0.42
TERRITORY_ALPHA = 0.34
TERRITORY_CELLS_PER_CITY = 45000
MAX_CITIES_PER_COUNTRY = 5
PORTS_PER_COUNTRY = 2

# 第五階段：時間、人口、資源與軍事。
WAR_START_YEAR = 1
INITIAL_POPULATION_PER_CELL = 2.4
INITIAL_SOLDIER_RATIO = 0.08
INITIAL_FLEET_PER_PORT = 18
ANNUAL_POPULATION_GROWTH = 0.006
ANNUAL_RECRUIT_RATIO = 0.012
MIN_GARRISON_RATIO = 0.035

# 行軍與補給。距離以地圖格計，1回合等於1年。
LAND_MARCH_CELLS_PER_YEAR = 38.0
SEA_MARCH_CELLS_PER_YEAR = 75.0
NAVAL_OPERATION_RANGE = 620.0
SUPPLY_PER_SOLDIER_CELL = 0.000018
SUPPLY_SHORTAGE_ATTRITION = 0.12
MOUNTAIN_DEFENSE_BONUS = 0.55
HILL_DEFENSE_BONUS = 0.22
RIVER_DEFENSE_BONUS = 0.12
AMPHIBIOUS_ATTACK_PENALTY = 0.28

# AI與戰爭節奏。
AI_WAR_CHECK_INTERVAL = 5
AI_BASE_WAR_CHANCE = 0.10
AI_MIN_ATTACK_SOLDIERS = 800
AI_MIN_POWER_RATIO = 1.08
AI_MAX_ACTIVE_CAMPAIGNS = 2
COALITION_THREAT_SHARE = 0.16
COALITION_MAX_MEMBERS = 5
CAPTURE_RADIUS_MIN = 10
CAPTURE_RADIUS_MAX = 36
BATTLE_RANDOMNESS = 0.12

# 聯盟援軍需要實際行軍；援助比例不會瞬間加到戰場。
ALLIANCE_COUNT = 6
ALLIANCE_REINFORCEMENT_RATIO = 0.18
